// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ContactHandler is an autogenerated mock type for the ContactHandler type
type ContactHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *ContactHandler) Add() {
	_m.Called()
}

// Delete provides a mock function with given fields:
func (_m *ContactHandler) Delete() {
	_m.Called()
}

// Detail provides a mock function with given fields:
func (_m *ContactHandler) Detail() {
	_m.Called()
}

// List provides a mock function with given fields:
func (_m *ContactHandler) List() {
	_m.Called()
}

// Update provides a mock function with given fields:
func (_m *ContactHandler) Update() {
	_m.Called()
}

type mockConstructorTestingTNewContactHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewContactHandler creates a new instance of ContactHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContactHandler(t mockConstructorTestingTNewContactHandler) *ContactHandler {
	mock := &ContactHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
